name: 'coverage-pull-request'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    jest-coverage-reporter:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm install
            - run: npm install -g jest
            - uses: juanmartinez-facephi/test-action@v2.0.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
